apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.33.3
apiServer:
  certSANs:
      - "api.k8s.mill.growse.com"
      - "localhost"
      - "serverbot"
      - "serverbot.mill.growse.com"
      - "2001:8b0:c8f:e8b0::9"
      - "kubernetes"
      - "kubernetes.default.svc"
      - "fd5a:1111:1111::1"
etcd:
  local:
    serverCertSANs:
      - "localhost"
      - "serverbot"
      - "serverbot.mill.growse.com"
      - "2001:8b0:c8f:e8b0::9"
    peerCertSANs:
      - "localhost"
      - "serverbot"
      - "serverbot.mill.growse.com"
      - "2001:8b0:c8f:e8b0::9"
