---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
localAPIEndpoint:
  advertiseAddress: "2001:8b0:c8f:e8b0::9"
---
apiServer:
  certSANs:
  - "fd5a:1111:1111::1"
  - k8s-api.growse.com
  - "2001:8b0:c8f:e8b0::9" 
  - "192.168.2.9"
  extraArgs:
    authorization-mode: Node,RBAC
    oidc-issuer-url: https://accounts.google.com
    oidc-client-id: 887447903183-k5d26153v3mamhhltubamchd1snalfqa.apps.googleusercontent.com
    oidc-username-claim: email
    feature-gates: "IPv6DualStack=true"
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    controllers: "*,bootstrapsigner,tokencleaner,-nodeipam"
dns:
  type: CoreDNS
etcd:
  local:
    serverCertSANs:
    - "etcd.k8s.growse.com"
    - "2001:8b0:c8f:e8b0::9"
    dataDir: /var/lib/etcd
    extraArgs:
      advertise-client-urls: https://[2001:8b0:c8f:e8b0::9]:2379
      initial-cluster: serverbot=https://[2001:8b0:c8f:e8b0::9]:2380
      initial-advertise-peer-urls: https://[2001:8b0:c8f:e8b0::9]:2380
      listen-client-urls: https://[::1]:2379,https://[2001:8b0:c8f:e8b0::9]:2379
      listen-metrics-urls: http://[::1]:2381
      listen-peer-urls: https://[2001:8b0:c8f:e8b0::9]:2380      

featureGates:
  IPv6DualStack: true
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v1.20.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: "fd5a:1111:1111::/112,10.96.0.0/12"
  podSubnet: "fd5a:5555:5555::/48,10.244.0.0/16"
scheduler: {}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "::"
cgroupDriver: "systemd"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
ipvs:
  strictARP: true
