apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: ce9xi2.at00ce4sm4p8ohuh
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 2001:8b0:c8f:e8b0::9
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: serverbot
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
---
apiServer:
  certSANs:
  - fd5a:1111:1111::1
  - 2001:8b0:c8f:e8b0::9
  - 192.168.2.9
  - api.k8s.mill.growse.com
  extraArgs:
    authorization-mode: Node,RBAC
    feature-gates: ""
    oidc-client-id: 887447903183-ff1kfifdfbniao4q69fdup4fqorkpsrt.apps.googleusercontent.com
    oidc-issuer-url: https://accounts.google.com
    oidc-username-claim: email
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes

dns: {}
etcd:
  
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: v1.30.0
networking:
  dnsDomain: k8s.mill.growse.com
  podSubnet: fd5a:5555:5555::/48,10.244.0.0/16
  serviceSubnet: fd5a:1111:1111::/112,10.96.0.0/12
scheduler:
  extraArgs:
    bind-address: ::1
    feature-gates: ""
